addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip, testbuild.zip]
    target_paths: baa8f935-0271-49d4-a925-370312a8bbf4
jdk: [oraclejdk8]
language: java
script: [mvn install, ./df-build.sh]
sudo: 'false'
# Modified by Insights Service at 2016-05-09 07:59:23.356738
